kumuluzee:
  name: comments-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://comments:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/CommentsDS
      connection-url: jdbc:postgresql://database-1.cgjpznojjyw2.eu-central-1.rds.amazonaws.com/comments
      username: dbuser
      password: logitech123
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.29.109:2379