kumuluzee:
  name: comments-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  datasources:
    - jndi-name: jdbc/CommentsDS
      connection-url: jdbc:postgresql://database-1.cgjpznojjyw2.eu-central-1.rds.amazonaws.com/comments
      username: dbuser
      password: logitech123
      max-pool-size: 20
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/CommentsDS
  metrics:
    web-instrumentation:
      - name: images-endpoint
        url-pattern: api/comments/*

configuration-properties:
  comments-properties:
    test-error: false